### ISSUE TITLE
Divide by 0 Error

### ISSUE THREAD

**Issue by francisyyan** [yzaki/verus#3]
Starting from the line 508 of `verus_server.cpp`

```
wBar += 1.0/wBar;

if(haveSpline)
    dEst = fmin (dEst, calcDelayCurveInv (wBar));
```

`wBar` can be 0 such that `wBar` then becomes infinity, which makes `calcDelayCurveInv` throw an exception "Spline1DCalc: infinite X!"

The error can be easily reproduced by running several times of client-server connection for 10 seconds. It can also be easily fixed by changing line 558 of `verus_server.cpp` into

```
wBar = fmax(1.0, fmin( wBar, VERUS_M_DECREASE * pdu->w));
```

because it is the `pdu->w` that makes `wBar` be 0 sometimes.

**Comment by yzaki** [comment]
Thanks for pointing this out. We have fixed the issue.
